### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by ohbob** [dasDaniel/svelte-table#11]
Please add demo to readme.

**Comment by dasDaniel** [comment]
there is a link to github pages for a demo: dasdaniel.github.io/svelte-table/
![image](https://user-images.githubusercontent.com/466865/88684487-c9170180-d0a9-11ea-92a9-abd1710592ff.png)

I would like to add some more demos with REPL though

**Comment by ohbob** [comment]
Thanks

**Comment by quantuminformation** [comment]
still missing

**Comment by dasDaniel** [comment]
there's a link on the about page, but here is is again: https://dasdaniel.github.io/svelte-table/

also some repl examples
* https://svelte.dev/repl/c0cc7945f59d40c3a542927c3cccf26b
* https://svelte.dev/repl/5a00064151594fcab50b4b0841d7d35a
* https://svelte.dev/repl/91c871dc626d40e0a5fac4296c9cdfe2
* https://svelte.dev/repl/8b2264e66d9a456abeb5f2b9322605f7
* https://svelte.dev/repl/4414e4c7e2494a5581abaec00497b7c1
* https://svelte.dev/repl/fbc7b02369b44612b22585d78a28048b
* https://svelte.dev/repl/7f392852bd434b3bbbe288db743e1756
* https://svelte.dev/repl/421014ce0a3c47a5a759d9bbe005277d
