### ISSUE TITLE
Cannot pass (custom) events to SvelteTable column component

### ISSUE THREAD

**Issue by rafalgradziel** [dasDaniel/svelte-table#110]
I would like to use Events and pass event handler (in my case custom event, but any event won't work) to column Component, and then use 
I tried to use `renderComponent.props` for that:
```
// MainFile.svelte
import MyCustomComponent from './MyCustomComponent.svelte';
const columns = [ {
  ...
  renderComponent: {
    component: MyCustomComponent,
    props: {
      "on:mycustomevent": myHandler
    }
  }
]

<SvelteTable columns={columns} rows={...} />
```
and then use:
```
// MyCustomComponent.svelte
import { createEventDispatcher } from 'svelte';
const dispatch = createEventDispatcher();
dispatch('mycustomevent', { .... });
```

but I get:
`<MyCustomComponent> was created with unknown prop 'on:mycustomevent'.`

I've tried with non-custom events, like "on:click" (and variants: "on_click", "onclick") but with same results.
How do I pass `on:xxxxx` props to component (while in this case I cannot use the regular `<MyCustomComponent on:xxx={...} />` approach)?

As current workaround I am passing a callback function as _prop_ to my component
```
<MyCustomComponent onMyEvent={myHandler} />
```
but use of Events has many other benefits (like: many listeners)

**Comment by dasDaniel** [comment]
unfortunately, this is an issue with svelte itself.

see: https://github.com/sveltejs/svelte/issues/5112

The issue can be boiled down to **Actions can only be applied to DOM elements, not components**

You can also look at this example (from the thread above) to see how they implemented a workaround https://svelte.dev/repl/f4b5f661bb7b40b7bd1272c1f58d2efc?version=3.24.1

The solutions relies on most of the functionality in the component. The props are passed as an object and then applied to the dom elements in it. I suspect you could setup something like that too. But it is a bit complicated and relies on adding the props and events manually through `use:attrs`.
