### ISSUE TITLE
Getting the count of filtered rows.

### ISSUE THREAD

**Issue by ctiospl** [dasDaniel/svelte-table#111]
Was wondering if it is possible to get the count of the filtered rows.
Thanks

**Comment by dasDaniel** [comment]
There is an exposed internal un-document variable called `c_rows` that you can get the value of 

```
<script>
  let filteredRows = [];
  //... etc
</script>

<SvelteTable columns="{columns}" rows="{rows}" bind:c_rows={filteredRows}/>
{ filteredRows.length }
```

This can give you the filtered columns.

Just note that due to the nature of undocumented features that rely on exposed internals, it could break in in some future release.

**Comment by davidnewhall** [comment]
Please consider exposing this and documenting it. I spent some time trying to figure this out before searching github issues. While it works, my typescript linter sure throws a fit about `c_rows` not existing .... I currently just want a simple count of the rows displayed, but having the rowKey (or all the data) would be nice so I can provide an `export` button next to the table.

**Comment by dasDaniel** [comment]
Updated and released in v0.6.5

**Comment by dasDaniel** [comment]
done

**Comment by dasDaniel** [comment]
done
