### ISSUE TITLE
how get filterOptions get reactive

### ISSUE THREAD

**Issue by spookyfox** [dasDaniel/svelte-table#12]
Hi Daniel,

Thx for sharing this lovely component. I would like to use it, but anyhow I do not know how to deal with the filter option.

I'm fetching some data from a REST API, once all data are there, I pass them to the `variable` **rows** and the data get rendered. but the list of filter values stay empty. Maybe you have an advice?

Thanks in advance,
Henrik

**Comment by dasDaniel** [comment]
It's a feature I'm hoping to add sometime.

In the meantime, one way to do it is using a component remount by toggling an encapsulating `if`

example using `remount`

```html
<script>
	let remount= true;
	fetch('***')
		.then(response => response.json())
		.then(json => {
			rows = json.data
			remount = false;
			setTimeout(() => remount = true, 0);
	});
</script>
{#if remount }
	<SvelteTable columns="{columns}" rows="{rows}"></SvelteTable>
{/if}
```

**Comment by spookyfox** [comment]
Hi Daniel,

thx a lot for your quick response and the solution you provided, which works well!
