### ISSUE TITLE
Allow user to define the search function

### ISSUE THREAD

**Issue by dasDaniel** [dasDaniel/svelte-table#120]
Currently the `searchValue` function returns a `string` that svelteTable compares internally to the search term. This is limiting the search functionality and prevents the user from defining search options like _starts with_ or _is case sensitive_. 

Instead the function should take the row **and** the search term as parameters and return a `boolean`. This will allow more flexibility in defining the search behaviour.

This change should allow both ways of using `searchValue` for backwards compatibility.

## TODO:

- add support for `searchValue(row:Object, searchTerm:string):boolean`
- maintain support for `searchValue(row:Object):string`
- update search example (Example5)
- update docs and include deprecation warning

**Comment by dasDaniel** [comment]
Released in v0.5.3: #120

**Comment by Saibamen** [comment]
#121
