### ISSUE TITLE
Search from Input

### ISSUE THREAD

**Issue by siva19susi** [dasDaniel/svelte-table#126]
Is there way to call search based on an independent `input[type=text]` field? All I see is adding `searchValue` as part of the column definition. Is `bind:filterSelections` the only approach for it?

**Comment by siva19susi** [comment]
Is `bind:filterSelections` the approach for it?

**Comment by siva19susi** [comment]
Well I took the reference from #119 and got it implemented. But how do I avoid the searchField right above the column?

**Comment by dasDaniel** [comment]
added ability to hide in `v0.5.5` using `hideFilterHeader`
