### ISSUE TITLE
Conditional Row Formatting

### ISSUE THREAD

**Issue by Tobfather** [dasDaniel/svelte-table#131]
Hi,

is it possible to format cells, rows (e.g. change background-color) based on row-data?

Best regards

Tobias

**Comment by dasDaniel** [comment]
Yes this is possible.

You can use `class` in the columns array for setting the class of individual cells, and you can use `classNameRow` for setting the class of a row dynamically. 

To use, pass a function to either of these.

Here is an example where a cell will use class `cell` if the row's id is even

```ts
    {
      key: "id",
      title: "ID",
      value: v => v.id,
      sortable: true,
      class: (v, r, c) => (v.id % 2 == 1 ? null : "cell"),
    },
```

Here is an example for having even/odd coloring (this may be helpful when the cells are expandeble)

```ts
const classNameRow: RowClassName<RowData> = (v, rowIndex) =>
    rowIndex % 2 == 0 ? null : "row-odd";
```


I went to reference the docs, but noticed that the cell functionality is not documented. 
I will need to update the documentation to include that. In the meantime, you can see the working example in https://github.com/dasDaniel/svelte-table/blob/develop/example/Example8.svelte

**Comment by Tobfather** [comment]
Hey Daniel, 
thank you so much,  for your fast and precise response, i really do appreciate that! Just tried it and it works like a charme! I think a short section about conditional formatting would make sense to be included in the docs. For example I didn't understand what the declaration of the function has to be like. From your example and testing I understood that it has to be like that (v = value, r = rowIndex and c = columnIndex). If not please correct me. I haven't found that information in the Docs, maybe I missed it. If not it would be helpfull if it was added. Thank you so much for this great library. It's very flexible and adoptable to ones needs! I enjoy using it!

**Comment by dasDaniel** [comment]
added info to docs
