### ISSUE TITLE
Add configurable placeholders to search inputs

### ISSUE THREAD

**Issue by Z0lid** [dasDaniel/svelte-table#134]

**Comment by dasDaniel** [comment]
Can you provide more detail or examples?

**Comment by Z0lid** [comment]
Well, [in SvelteTable.svelte line 303](https://github.com/dasDaniel/svelte-table/blob/d59558a43e1e32d2486eb29d5d18d90f4c86d4ea/src/SvelteTable.svelte#L303) you could add a `placeholder` attribute that can be configured from, for example `col.searchPlaceholder`.

**Comment by dasDaniel** [comment]
gotcha 👍
