### ISSUE TITLE
Column selection not working

### ISSUE THREAD

**Issue by skelbojann** [dasDaniel/svelte-table#139]
Hi, 

in the current version 0.5.6 the column selection has a bug.
You can reproduce it in the example 3 of the repository when trying to show the IPs.
It seems that the table tries to access columns that have been removed from the columns array:
`Uncaught (in promise) TypeError: Cannot convert undefined or null to object`

In my table I get a similiar error:
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'searchValue')`

![image](https://user-images.githubusercontent.com/27064905/227929982-32037f6b-41e8-4d3d-ab20-0591729c1f04.png)

**Comment by dasDaniel** [comment]
Thanks for reporting.

This is an issue in the example itself and not the library. I've made the fix (in the develop branch). I won't be publishing a separate version for this fix though, so it won't make it out until there's a change to the library itself.

**Comment by dasDaniel** [comment]
The error `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'searchValue')` seems to indicate that the the lib cannot find the object in the column. 
Can you provide an example/repl for the error you are seeing?

**Comment by dasDaniel** [comment]
Thanks, I see the issue.
I think this is related to a combination of filters and columns being removed, which Example3 doesn't cover. I will need to figure out a solution for this.

**Comment by skelbojann** [comment]
Awesome, thanks for the reponse. Looking forward to a fix!

**Comment by dasDaniel** [comment]
fixed in v0.5.7
- #142 
- #141

**Comment by skelbojann** [comment]
Awesome work, thanks for the fast fix!
