### ISSUE TITLE
Types: searchValue type is incorrect

### ISSUE THREAD

**Issue by Z0lid** [dasDaniel/svelte-table#149]
In [types.d.ts line 11](https://github.com/dasDaniel/svelte-table/blob/develop/src/types.d.ts#L11) the `searchValue` property isnt typed according to the readme, the readme even specifies that `searchValue` has 2 options. My proposed solution is to change the `searchValue` type to something like `((row: T) => string) | ((row: T, searchTerm: string) => boolean)`.

**Comment by dasDaniel** [comment]
thanks, fixed and released
