### ISSUE TITLE
Remove sorting on 3rd click?

### ISSUE THREAD

**Issue by Z0lid** [dasDaniel/svelte-table#150]
I think it is expected from the end user to be able to remove the sorting on the 3rd click on the sorted column. It is not a priority, but i'd be nice to have.
Any thoughts on this?

**Comment by dasDaniel** [comment]
This feature is available by manually assigning `sortOrders` 

```js
sortOrders={[-1, 1, 0]}
```

see https://github.com/dasDaniel/svelte-table/blob/develop/example/Example3.svelte#L258
