### ISSUE TITLE
Text input as filter

### ISSUE THREAD

**Issue by JAIC-be** [dasDaniel/svelte-table#16]
Is there a way to have a text input as filter instead of dropdowns?

Thanks

**Comment by dasDaniel** [comment]
Not at the moment. 

I'll look into supporting it

**Comment by dasDaniel** [comment]
added to version 0.1.13 #18 

use `search` in columns definition 

ie:
```    {
      key: "first_name",
      title: "FIRST NAME",
      value: v => v.first_name,
      sortable: true,
      search: v => v.first_name
    },
```

Currently is not configurable for additional options. Is not case sensitive and looks for matches anywhere in the string (not starts with).

**Comment by dasDaniel** [comment]
example : https://svelte.dev/repl/4414e4c7e2494a5581abaec00497b7c1
