### ISSUE TITLE
How do I set expanded to true for all rows?

### ISSUE THREAD

**Issue by RicardoViteriR** [dasDaniel/svelte-table#164]
hello, is there a way to set expanded to true for all rows? I'd like to be able to load the table with each row expanded by default. Thank you.

**Comment by dasDaniel** [comment]
you can use the `expanded` prop and pass it every item.

see tis section for details https://github.com/dasDaniel/svelte-table#expanding-rows

example would be to set `rowKey` to `id`, and then pass every row's id to the `expanded` prop
