### ISSUE TITLE
v0.6.2 breaks SvelteKit build

### ISSUE THREAD

**Issue by leonklingele** [dasDaniel/svelte-table#168]
Hi there 😊

The most recent release, v0.6.2, unfortunately breaks our build using SvelteKit:

```
> svelte-kit sync && svelte-check --tsconfig ./tsconfig.json
====================================
Loading svelte-check in workspace: /path/to/project
Getting Svelte diagnostics...
/path/to/project/…:
Error: Cannot find module 'svelte-table' or its corresponding type declarations. (ts)
	import SvelteTable from 'svelte-table';
…
```

v0.6.1 was working fine. Is there any workaround we need to apply to get this project running again using SvelteKit?

Thanks for helping!

Refs. https://github.com/dasDaniel/svelte-table/pull/166

**Comment by dasDaniel** [comment]
thanks for reporting, clearly the change to exports for `vite-plugin-svelte` does not work for `svelte-kit`. I'll try and find a way to get them both to work. For now, please use `"svelte-table": "0.6.1",` as the dependency.

**Comment by dasDaniel** [comment]
@leonklingele found the issue. Should be good now. Released fix in `0.6.3`

**Comment by Saibamen** [comment]
Fixed by https://github.com/dasDaniel/svelte-table/commit/ec1b6c2ea86f79963c6b3f2b3d88be00be53987b

**Comment by leonklingele** [comment]
Builds fine again 😃 Thanks for the quick fix!
