### ISSUE TITLE
Make sortByValue configurable

### ISSUE THREAD

**Issue by cheapjoe** [dasDaniel/svelte-table#19]
Hello,

I noticed a problem when I wanted to display currency data in a table (e. g. "19,51 €"). The sort function didn't work, because in its logic the string "19,51 €" comes before "2,24 €" before "24,22 €" before "3,02 €".

The problem was of course that svelte-table handles these values as a string and therefore technically it's sorted correctly. I made a little adjustment that provides an optional column parameter (sortByValue) to set a different sort value than the original displayed value.

I didn't open a pull request, because I guess this could be done also a bit more clean and less dirty.
If this already can be done somehow and I just missed it in the documentation, I'm sorry and you can just ignore this issue.

```javascript
$: {
      let col = columnByKey[sortBy];
      if (col !== undefined && col.sortable === true && typeof col.value === "function") {
        sortFunction = typeof columnByKey[sortBy].sortByValue == "undefined" ? r => col.value(r) : columnByKey[sortBy].sortByValue;
      }
    };
```

Thank you for providing this awesome svelte component! :)

**Comment by dasDaniel** [comment]
This may be unnecessary, you should be able to use `value` for sorting and `renderValue` for display

here is an example
https://svelte.dev/repl/421014ce0a3c47a5a759d9bbe005277d?version=3.29.6
