### ISSUE TITLE
How to clear filter/searchValue?

### ISSUE THREAD

**Issue by ar-jan** [dasDaniel/svelte-table#29]
I'm new to Svelte and this should probably be obvious, but how do I access/set the `searchValue` value from my own function? I want to create a button to clear the user-entered values passed to the `searchValue` defined for several columns.

**Comment by dasDaniel** [comment]
I don't think that's possible at the moment. 
Ideally search and filter variables would be accessible and reactive, I will work on a fix for this.

**Comment by ar-jan** [comment]
Great! And thanks for the plugin, very useful.

**Comment by dasDaniel** [comment]
fixed in v0.0.17
