### ISSUE TITLE
I want to use select multiple. How to modify code ? 

### ISSUE THREAD

**Issue by luddwskater** [dasDaniel/svelte-table#32]

**Comment by dasDaniel** [comment]
Need to replace select with a multi-select at https://github.com/dasDaniel/svelte-table/blob/develop/src/SvelteTable.svelte#L139
You may be able to use `<select multiple>`  or create a similar implementation

this will make the bound `filterSelections[col.key]` an array, you can then adjust [L41-L43](https://github.com/dasDaniel/svelte-table/blob/develop/src/SvelteTable.svelte#L41-L43) to look for matches in the array

**Comment by luddwskater** [comment]
Thank you, it works.
Ludwik
