### ISSUE TITLE
Handle dynamic column definitions correctly

### ISSUE THREAD

**Issue by dennisjlee** [dasDaniel/svelte-table#33]
I have a situation where my column definitions are dynamic (based on a toggle in the UI). It's similar to this:

```
let columns = showDailyMax ? [
  { 
    key: 'sales',
    title: 'Sales (daily max)',
    value: row => row.dailyMaxSales
  }
] : [
  { 
    key: 'sales',
    title: 'Sales (annual)',
    value: row => row.annualSales
  }
];
```

And then I pass the dynamic `columns` variable into `<SvelteTable>`. (I set up those columns with the same key so that when the user toggles, that column will remain sorted if it was before.)

When I do this, there's a bug in how SvelteTable handles sorting, due to the fact that the `columnsByKey` variable isn't declared in a reactive way. The table will still be sorted by the daily max column definition (because `columnsByKey['sales']` will still have that cached value) instead of the annual column definition.

**Comment by dasDaniel** [comment]
released v0.1.18
