### ISSUE TITLE
Sort on component cell

### ISSUE THREAD

**Issue by VirgileD** [dasDaniel/svelte-table#36]
Hello, nice component!
Am I right to say that if there are component, sorting does not work?
It seems (but maybe I did smthing wrong) that when some cells are component and you click on the header to sort the table, only the columns that are simple values will be sorted, the columns that are components don't change?

**Comment by dasDaniel** [comment]
Can you create share a repl with example?

**Comment by jiyosub** [comment]
I am having this issue also.

**Comment by jiyosub** [comment]
Fixed my issue.  Forgot to include $ to make my component reactive.
