### ISSUE TITLE
Is there a way to handle bind:propName when using renderComponent?

### ISSUE THREAD

**Issue by mnemyx** [dasDaniel/svelte-table#37]
I really like this library for its flexibility, but I have an instance where a property can change in the child component (rendered in a cell of the svelte-table) and needs to be propagated back to the parent component (the svelte-table). The easiest way to handle this is through bindings in svelte (https://svelte.dev/tutorial/text-inputs) but I don't think there's a way for me to use that directive when using renderComponent?

**Comment by dasDaniel** [comment]
Hi Gina, could you provide an example repl for this?

**Comment by malomarrec** [comment]
Related: it'd be useful to be able to do something like:

```typescript
colUsers=[
	{
		key: 'contact',
		title: '',
		sortable: false,
		renderValue: (v) => <button on:click={clickHandler}>${v.email}</button>`
	}]
```
