### ISSUE TITLE
Horizontal scroll?

### ISSUE THREAD

**Issue by JhojanFlp** [dasDaniel/svelte-table#39]
My table has many columns, is there any configuration to have horizontal scrolling?

**Comment by dasDaniel** [comment]
Not directly, but can be achieved with classes or add your own rules with `nth` selectors to target a specific column.

### Component Props (top level)

Option | Type | Description
-- | -- | --
classNameTable | String/Array | *optional* class name(s) for table element
classNameThead | String/Array | *optional* class name(s) for thead element
classNameTbody | String/Array | *optional* class name(s) for tbody element
classNameSelect | String/Array | *optional* class name(s) for select elements
classNameRow | String/Array | *optional* class name(s) for row elements
classNameCell | String/Array | *optional* class name(s) for cell elements

## Column Objects (column-specific)

Option | Type | Description
-- | -- | --
class | String | *optional* table cell class name
headerClass | String | *optional* class to assign to header


You will likely need to use `display:block` though and define absolute widths

Example:

https://svelte.dev/repl/5d2248d049ff413fba63154ee35e355e

```html
<style>
  :global(table) {
    overflow-x: scroll;
  }
  :global(table thead, table tbody) {
    display: block;
    width: 1200px;
  }
  :global(thead tr th, tbody tr td) {
    width: 80px;
  }
  :global(th:nth-child(4), td:nth-child(4)) {
    width: 400px;
  }
  :global(th:nth-child(6), td:nth-child(6)) {
    width: auto;
  }
</style>
```
