### ISSUE TITLE
Not rendering table?

### ISSUE THREAD

**Issue by kgonzale** [dasDaniel/svelte-table#50]
Currently my project is set up like this -> 

```js
<script>
  	import SvelteTable from "svelte-table";

let rows = [];

querySomething.forEach(i => rows.push(i))
</script>

<SvelteTable columns="{columns}" rows="{rows}"></SvelteTable>

```

then I push an object into the rows, where <SvelteTable columns="{columns}" rows="{rows}"></SvelteTable> is declared outside of the script but the table is not rendering to show the new rows... why?

**Comment by dasDaniel** [comment]
This is a svelte "issue", where `push` is not reactive. try reassigning the `rows` array instead 

could do: 
```js
querySomething.forEach(i => rows = [...rows,i])
```

more [info/example](https://svelte.dev/tutorial/updating-arrays-and-objects)

**Comment by kgonzale** [comment]
Question, if I wanted to add a component to the table itself in a column, say delete a row, can you give an example of this?

**Comment by dasDaniel** [comment]
No unfortunately not. I think this is probably the biggest shortcoming of the table at the moment. I'm hoping to add that feature sometime, but there's no WIP for that at the moment.
However, the table is built in a way that makes it relatively easy to copy-paste and implement a custom feature
