### ISSUE TITLE
How do you set the width of a cell?

### ISSUE THREAD

**Issue by flooyd** [dasDaniel/svelte-table#56]
example column
{
key: "blah"
...
...
class: "tableCell"
}

style

.tableCell {
width: 200px
}

I also tried min-width and max-width but apparently these don't apply to td elements. I also tried :global(.tableCell)

**Comment by dasDaniel** [comment]
I'm guessing the reason you are seeing that is that the svelte scopes the class to the component. 

Wrapping your class with `global`, like:  `:global(.tableCell) {` will allow the child component to use the style

For more info in how the scoping works have a look at https://svelte.dev/docs#style

Another way to alter the widths, though it shouldn't be necessary, is to us the `nth-child` selector, but the `global` is still required.

```css
:global(th:nth-child(4), td:nth-child(4)) {
  width: 200px;
}
```

**Comment by flooyd** [comment]
I tried the former and it doesn't work. I can set background color, padding, etc. but width 200px doesn't apply😔

**Comment by flooyd** [comment]
Maybe it's because I didn't apply same style to header...

**Comment by dasDaniel** [comment]
should work, but the header will limit it based on content too

use `max-width` and apply to header via `headerClass`

example: https://svelte.dev/repl/f0d3b564efeb45c895c0ddba34f05216

**Comment by flooyd** [comment]
It's still not working :( could you take a look at this code if you get a chance

https://github.com/flooyd/mango/blob/master/client/src/components/MatchDetails.svelte

**Comment by flooyd** [comment]
I used display table-cell and now it works as I expect.

**Comment by dasDaniel** [comment]
it's not clear what you want the behaviour to be. but I did notice one thing. If you want .tableCell to be "200px` and .tableHero is already a fixed width, browsers cannot honor all the widths and fill the width still, so the values will get re-calculated. You could set the `tableHero` to have the % witdh to fill the space (assuming you want the other columns to have the pixel based width)
