### ISSUE TITLE
Is there a way of highlighting the expanded row ant its details

### ISSUE THREAD

**Issue by albu77** [dasDaniel/svelte-table#59]
As the title says, I would like to emphasize  the selected row and it's details so wondering if there is already something either in `SvelteTable `or in your` example7` which could do the trick. Without it ( I didn' find anything...) I think I will need to modify the code in the `SvelteTable component` code to add a class on both tr: the one which trigger the expansion and the expanded one...
Any advice  would be appreciated greatly...

**Comment by dasDaniel** [comment]
The prop `classNameRowExpanded` handles the content, but there is no way to do that with the actual row.

Unfortunately the class name is not appropriate, and will require a breaking change to be "intuitive". And the expanded content row should have a name like `classNameExpanded` or `classNameExpandedContent`

**Comment by dasDaniel** [comment]
fixed release with v0.3.0
