### ISSUE TITLE
Feature: reactivity so you can update the data and generate columns programatically for it

### ISSUE THREAD

**Issue by theWebalyst** [dasDaniel/svelte-table#6]
Firstly, thanks for a very helpful component!

This is to share that I made a fork which adds reactivity, explained [here](https://github.com/theWebalyst/svelte-table#reactivity). The changes are minor, and I tweaked the README in a couple of places (as well as documenting the 'reactivity' feature.

The feature can be seen in use in my [Visualisation Lab](https://github.com/theWebalyst/visualisation-lab) project. It is a work in progress, but usually up to date at http://vlab.happybeing.com

Hope the fork is of interest. Let me know if you would like a PR.

**Comment by dasDaniel** [comment]
Hello, thanks for the contributions. Haven't had much time to review this lately, I'll try to incorporate when I have some time.

**Comment by eamag** [comment]
I would like to see a PR :)

**Comment by theWebalyst** [comment]
Here is the PR:

https://github.com/dasDaniel/svelte-table/pull/10

**Comment by dasDaniel** [comment]
Sorry for taking so long to get to this. I've finally had some time to look into this. I've started by updating the examples to setup an environment to test this in.
I've found that the reactivity worked without needing any changes to the `svelte-table` component. 

Maybe you can look at the setup of [example 3](https://github.com/dasDaniel/svelte-table/blob/master/example/Example3.svelte) 
The rows and columns are reactive in the example component.

**Comment by theWebalyst** [comment]
No problem. I've added a note to my fork/PR to look at this and so others can find it [here](https://github.com/theWebalyst/svelte-table/tree/enhancment-add-reactivity#reactivity).

**Comment by rottmann** [comment]
@dasDaniel Filter are not reactive, should update filterOptions and filterValue on row-change.

**Comment by dasDaniel** [comment]
should be resolved with last release 0.1.11
example: https://svelte.dev/repl/8b2264e66d9a456abeb5f2b9322605f7
