### ISSUE TITLE
Expanded Row

### ISSUE THREAD

**Issue by albu77** [dasDaniel/svelte-table#72]
I came back with breakpoints notion for columns.
I'm trying to work on your code but it's really hard for me.
I'm trying to do the following:
1°) Add device resolution changes: Ok done by creating a store and doing an `import watchMedia from "svelte-media";` and declaring : 
```const mediaqueries = {  xs: "(max-width: 480px)",  sm: "(max-width: 768px)",  md: "(max-width: 992px)",  lg: "(min-width: 993px)" ```
2°) Modify the `const COLUMNS = {` declaration by adding the fields which would be affected by the space available on the device screen. 
A column could either be directly shown whatever is the device screen (xs, sm, md or lg)
Or a column could be linked to one or multiple breakpoints 
- no breakpoints means the column is always visible 
- **all** means this field will be shown in the expanded detail table whatever is the screen size
- **xs,sm,md lg** means this field will be shown in the expanded detail table for one or a combination of sizes (could be for example [xs,sm]

I've seen that actually the expanded data have no header and the colspan of the detail table is linked to the real columns displayed
3°) So I need to make the selected columns `selectedCols `to depend on the columns description    
4°) the actual expanded3 (for exemple in Example7.svelte should be also replace by an array depending on the columns description and bind to the watchMedia store
Here are my first thoughts and I found these a good objective for me to learn Svelte but It sounds easier that it is...
Could you tell me if you are working on such points

**Comment by dasDaniel** [comment]
I'd like to keep the package minimal and am not looking to include dependencies or implement breakpoints.
However, if there is some internal that the library can expose to make it easier, I can include that.

Can you create a REPL with what you have sofar?

**Comment by albu77** [comment]
I will try to make a repl after Xmas
