### ISSUE TITLE
switch beetween ASC, DESC, NO filter

### ISSUE THREAD

**Issue by Ennoriel** [dasDaniel/svelte-table#73]
Hello,

It's me again.

When clicking on a column, if the column is sortable, it is sorted ASC, then DESC and there is no way to remove the sorting criteria. I would maybe suggest to have a prop to either switching from ASC to DESC or from ASC to DESC to NO filter. Also, usually, when a column if sortable, there is a two-arrow icon indicating that the column is sortable.

I haven't tried but it is theoretically possible to override this behavior with the exposed clickCol event and sortorder / sortby props.

If you find this relevant, I can submit a PR.

**Comment by dasDaniel** [comment]
That sounds useful.

I'm thinking [this part](https://github.com/dasDaniel/svelte-table/blob/develop/src/SvelteTable.svelte#L178-L184)
would use an array for sort order and the default would be the first value, so `[1, -1]` would be the current functionality and setting to `[1, -1, 0]` would be the functionality you describe. I think for ease of use, order consts like `ORDER_ASC` could be exported through module script since they are more intuitive than using number values.

```js
  const updateSortOrder = colKey => {
    if (colKey === sortBy) {
      sortOrder = sortOrder === 1 ? -1 : 1;
    } else {
      sortOrder = 1;
    }
  };
```

the one thing I'm not sure on is whether a setting of `0` would just propagate to the filter or if the `updateSortOrder` method should treat 0 as `sortBy = ""` thereby clearing the sort setting (so `[1, 0 ,-1]` could never reach `-1` value)

**Comment by Ennoriel** [comment]
Your idea of a sortOrders prop is great ! That would also allow anyone to order ASC or DESC first.

I would go with something like this:

``` javascript
export let sortOrders = [1, -1]

const updateSortOrder = colKey => {
    if (colKey === sortBy) {
        sortOrder = sortOrders[(sortOrders.findIndex(o =>  o === sortOrder) + 1) % sortOrders.length];
    } else {
        sortOrder = 1;
    }
};
```

Also, I prefer having a method that returns a value (setOrder) to have tests ;)

<details>
<summary>Jest tests</summary>

``` javascript
test('updateSortOrder', () => {
    // const updateSortOrder = (colKey, sortBy, sortOrder, sortOrders)

    expect(updateSortOrder('name', 'year', undefined, [1, -1])).toStrictEqual(1);
    expect(updateSortOrder('name', 'year', undefined, [1, -1, 0])).toStrictEqual(1);

    expect(updateSortOrder('name', 'name', undefined, [1, -1])).toStrictEqual(1);
    expect(updateSortOrder('name', 'name', 1, [1, -1])).toStrictEqual(-1);
    expect(updateSortOrder('name', 'name', -1, [1, -1])).toStrictEqual(1);

    expect(updateSortOrder('name', 'name', undefined, [1, -1, 0])).toStrictEqual(1);
    expect(updateSortOrder('name', 'name', 1, [1, -1, 0])).toStrictEqual(-1);
    expect(updateSortOrder('name', 'name', -1, [1, -1, 0])).toStrictEqual(0);
    expect(updateSortOrder('name', 'name', 0, [1, -1, 0])).toStrictEqual(1);
})
```

</details>

**Comment by dasDaniel** [comment]
agreed, a functional approach is better. And aaving `handleClickCol` pass the variables could make easier to add later the ability to configure sort order per-column.

**Comment by Ennoriel** [comment]
I came up with a question: I know that it would be a breaking changes, but, does it make sense to have ASC/DESC by default without the opportunity to unset a filter?
If you want me to submit a PR, let me know.

**Comment by dasDaniel** [comment]
Unless there's a compelling reason I would keep default as ASC/DESC without ability to unset.
I don't want to introduce breaking changes, and default sorting should be supplied (and the docs should probably make that clear)

a PR is welcome, thanks

**Comment by dasDaniel** [comment]
Thanks
Merged, build and pushed to [npm](https://www.npmjs.com/package/svelte-table) under v0.3.3
