### ISSUE TITLE
Table CSS header fix

### ISSUE THREAD

**Issue by kuhlaid** [dasDaniel/svelte-table#8]
Tried to make a slight fix to the CSS in the table header but if I leave out the comma then the col.headerClass does not get added to the HTML. Any ideas?
[https://github.com/kuhlaid/svelte-table/commit/90bcd4eaccfa6be077c2504616d11c07ff516244](https://github.com/kuhlaid/svelte-table/commit/90bcd4eaccfa6be077c2504616d11c07ff516244)

**Comment by dasDaniel** [comment]
Unfortunately, this does not render the intended output, but I fixed the asStringArray function in v0.1.8 so it should render result correctly.

Thanks for pointing this issue out.
