### ISSUE TITLE
How can I make merged table head?

### ISSUE THREAD

**Issue by cokiet12** [dasDaniel/svelte-table#80]
Can I implement this table with merged cells and header using svelte-table?

![image](https://user-images.githubusercontent.com/57649394/173265307-63da609e-fdaa-4806-9890-53c4a1247cd8.png)

Your prompt response would be much appreciated.

**Comment by dasDaniel** [comment]
That's not possible with this component. You might be able to use the row slot to get that to work, but I don't know if it's worthwhile. If you don't need the sorting and filtering functionality, it's probably easier to just implement a simple table yourself. If you do need sorting, with multiple rows being grouped, this might need more logic, but the source is in a single file and fairly simple, so you could also adjust it to suit your needs.

**Comment by dasDaniel** [comment]
If you're only looking to add a merged head without any additional functionality or having merged rows, you can use the `header` slot to replace the header with custom html
