### ISSUE TITLE
<SvelteTable> was created with unknown prop 'classNameRowSelected'

### ISSUE THREAD

**Issue by Saibamen** [dasDaniel/svelte-table#96]
Code:

```js
<SvelteTable
	columns="{columns}"
	rows="{rows}"
	classNameTable="border-2 border-collapse mt-4 mb-4"
	classNameThead="border-2 border-collapse"
	classNameRow="border-2 border-collapse odd:bg-gray-100 hover:bg-gray-300"
	classNameCell="pr-4"
	classNameRowSelected="bg-gray-500" />
```

Version: 0.3.5

**Comment by Saibamen** [comment]
Ahh sorry, after installing 0.4.5 (and adding `"typescript": "^4.7.4"` into `package.json`), I have different error:

```
error TS6053: File 
'@tsconfig/svelte/tsconfig.json' not found.
```

**Comment by Saibamen** [comment]
Without `typescript` installed, I have this error:

```
[vite] Internal server error: Error while preprocessing C:/myApp/node_modules/svelte-table/src/SvelteTable.svelte - Cannot find module 'typescript'
Require stack:
- C:\myApp\node_modules\svelte-preprocess\dist\transformers\typescript.js
- C:\myApp\node_modules\svelte-preprocess\dist\autoProcess.js
- C:\myApp\node_modules\svelte-preprocess\dist\index.js
- C:\myApp\svelte.config.cjs
- C:\myApp\node_modules\@sveltejs\vite-plugin-svelte\dist\index.cjs
  Plugin: vite-plugin-svelte
  File: C:/myApp/node_modules/svelte-table/src/SvelteTable.svelte
      at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
      at Function.Module._load (node:internal/modules/cjs/loader:778:27)
      at Module.require (node:internal/modules/cjs/loader:1005:19)
      at require (node:internal/modules/cjs/helpers:102:18)
      at Object.<anonymous> (C:\myApp\node_modules\svelte-preprocess\dist\transformers\typescript.js:8:38)
      at Module._compile (node:internal/modules/cjs/loader:1105:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
      at Module.load (node:internal/modules/cjs/loader:981:32)
      at Function.Module._load (node:internal/modules/cjs/loader:822:12)
      at Module.require (node:internal/modules/cjs/loader:1005:19)
```

**Comment by dasDaniel** [comment]
I think adding typescript added some issues that are just not worth the benefit. 
I think I'll remove typescript support

**Comment by dasDaniel** [comment]
> Ahh sorry, after installing 0.4.5 (and adding `"typescript": "^4.7.4"` into `package.json`), I have different error:
> 
> ```
> error TS6053: File 
> '@tsconfig/svelte/tsconfig.json' not found.
> ```

you can install `"@tsconfig/svelte": "^3.0.0",` to address that. It should be the only requirement necessary. I think if I put it into dependencies, it would resolve it, but I'll just remove ts

**Comment by dasDaniel** [comment]
typescript was removed #98 you should be able to use with `v0.5.0`

**Comment by Saibamen** [comment]
> > Ahh sorry, after installing 0.4.5 (and adding `"typescript": "^4.7.4"` into `package.json`), I have different error:
> > ```
> > error TS6053: File 
> > '@tsconfig/svelte/tsconfig.json' not found.
> > ```
> 
> you can install `"@tsconfig/svelte": "^3.0.0",` to address that. It should be the only requirement necessary. I think if I put it into dependencies, it would resolve it, but I'll just remove ts

This fixed the issue



> typescript was removed #98 you should be able to use with `v0.5.0`

Thanks
